const data = {
    products: [
      {
        _id: '1',
        name: 'Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band',
        category: 'Shirts',
        image: '/images/watch.webp',
        price: 80.00,
        disPrice: 60,
        initialStock: 1000,
        countInStock: 500,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality product',
        Promotag : 'buy 3 to get addition 10% off',
        isFreeshipping : true,
      },
      {
        _id: '1',
        name: 'Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band',
        category: 'Shirts',
        image: '/images/watch.webp',
        price: 80.00,
        disPrice: 60,
        initialStock: 1000,
        countInStock: 500,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality product',
        Promotag : 'buy 3 to get addition 10% off',
        isFreeshipping : true,
      },
      {
        _id: '1',
        name: 'Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band',
        category: 'Shirts',
        image: '/images/watch.webp',
        price: 80.00,
        disPrice: 60,
        initialStock: 1000,
        countInStock: 500,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality product',
        Promotag : 'buy 3 to get addition 10% off',
        isFreeshipping : true,
      },
      {
        _id: '1',
        name: 'Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band',
        category: 'Shirts',
        image: '/images/watch.webp',
        price: 80.00,
        disPrice: 60,
        initialStock: 1000,
        countInStock: 500,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality product',
        Promotag : 'buy 3 to get addition 10% off',
        isFreeshipping : true,
      },
      {
        _id: '1',
        name: 'Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band',
        category: 'Shirts',
        image: '/images/watch.webp',
        price: 80.00,
        disPrice: 60,
        initialStock: 1000,
        countInStock: 500,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality product',
        Promotag : 'buy 3 to get addition 10% off',
        isFreeshipping : true,
      },
      {
        _id: '1',
        name: 'Silicone Strap For Apple Watch Band 44mm 40mm 45mm 41mm 49mm 42mm 38mm 44 45 mm bracelet iwatch series 7 se 3 4 5 6 8 Ultra band',
        category: 'Shirts',
        image: '/images/watch.webp',
        price: 80.00,
        disPrice: 60,
        initialStock: 1000,
        countInStock: 500,
        brand: 'Nike',
        rating: 1.5,
        numReviews: 10,
        description: 'high quality product',
        Promotag : 'buy 3 to get addition 10% off',
        isFreeshipping : true,
      },
    ],
  };
  
  export default data;
  